spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver:${db_host};databasename=${db_schema}
#    url: jdbc:sqlserver://d20g828603.iok.la:25010;databasename=PROCESS_DATA
#    url: jdbc:sqlserver://127.0.0.1:65397;databasename=PROCESS_DATA
    username: ${db_username}
    password: ${db_password}

mybatis-plus:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/**.xml
  global-config:
    banner: false