server:
  port: 10010
  servlet:
    context-path: /

spring:
  messages:
    basename: i18n/messages
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: static/**
  application:
    name: mes-edge-portal-ms
  config:
    location: classpath:/,file:config/
  profiles:
    include: db-mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
  cloud:
    loadbalancer:
      retry:
        enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml

management:
  endpoint:
    health:
      show-details: never
    shutdown:
      access: read_only
  endpoints:
    web:
      base-path: ${server.servlet.context-path}
      exposure:
        include:
          - "health"
          - "shutdown"
security:
  oauth2:
    resource:
      jwk:
        key-set-uri:
ribbon:
  restclient:
    enabled: true
  okhttp:
    enabled: true
era:
  log:
    level: info
    file:
      path: log/
  permission:
    ignore:
      auth_check:
        - /expose/**
        - /
        - /templates/**
        - /view/**
        - /winCCReport/**
      api_check:
        - /expose/**
        - /
        - /templates/**
        - /view/**
        - /winCCReport/**
  token:
    store-type: Db
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 10000
mqtt:
  server-uri:
    - tcp://127.0.0.1:1883
#  username: ms-dts
#  password: P2c6wkaN5WZPJcGEedaF
  client-id: ds-dts
#logging:
#  level:
#    org:
#      springframework:
#        ws: TRACE
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true